export const CLEAR_FILTER = "CLEAR_FILTER";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const REGISTER_FORM_UPDATE = "REGISTER_FORM_UPDATE";
export const CREATE_ALERT = "CREATE_ALERT";
export const DELETE_ALERT = "DELETE_ALERT";
export const GET_USERADS_SUCCESS = "GET_USERADS_SUCCESS";
export const GET_USERADS_FALIURE = "GET_USERADS_FALIURE";
export const SET_AD_FORM_DATA = "SET_AD_FORM_DATA";

//Profile page
export const TOGGLE_EMAIL_EDITING = "TOGGLE_EMAIL_EDITING";
export const CLOSE_EDITING = "CLOSE_EDITING";
