import Head from "next/head";
import Header from "../components/globals/header/Header";
import HomePage from "../components/pages/home/HomePage";
import Footer from "../components/globals/footer/Footer";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Auto Bizz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <HomePage />
        <Footer />
      </main>
    </div>
  );
};

export default Home;
