import Head from "next/head";
import Header from "../components/globals/header/Header";
import HomePage from "../components/pages/home/HomePage";
import Footer from "../components/globals/footer/Footer";
import axios from "/axios/index.js";
import { getCars } from "./apiCalls";

const Home = (props) => {
  return (
    <div>
      <Head>
        <title>Auto Bizz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage carsArray={props.data} />
      </main>
    </div>
  );
};

export async function getStaticProps() {
  let result = await getCars();
  return {
    props: { data: result.data },
  };
}

export default Home;
